### ISSUE TITLE
Lock-up's incentive is not implemented.

### ISSUE THREAD

**Issue by aggre** [dev-protocol/protocol#140]
# Problem subject

- [x] Contracts
- [ ] Tests
- [ ] Other

# Description

A lockup invoker is entitled to a portion of a market reward.

Of the total amount of market reward per Property, `holdersShare` is a receiving amount of Property holder. This is confirmed by a call to `increment`. Of the total amount of market reward per Property minus the `holdersShare` is the incentive for the lockup invoker.

# Expected behavior/contents

Hmm, no idea yet...

# Actual behavior/contents

Not implemented.

# Code of Conduct

By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/dev-protocol/repository-token/blob/master/CODE_OF_CONDUCT.md) 🖖

**Comment by Akira-Taniguchi** [comment]
memo

```
新しくイシューあげたのですが、ロックアップ実行者のインセンティブが未実装かつ手法も確立していません。

https://github.com/dev-protocol/protocol/issues/140
GitHub
Lock-up's incentive is not implemented. · Issue #140 · dev-proto...
Problem subject Contracts Tests Other Description A lockup invoker is entitled to a portion of a market reward. Of the total amount of market reward per Property, holdersShare is a receiving amount...

Propertyホルダーのインセンティブ(マーケット報酬)は、PropertyがERC20ゆえに、自身が受け取れる権利の数を計算しやすいです。ロックアップ実行者の場合は、自分以外の者によってロックアップが増えることで、相対的に自分の権利の数が減る可能性があります。このことを考慮すると、完全に公平な計算は難しいかもしれません。
```

**Comment by aggre** [comment]
I have an idea. Basically, that can use the same calculations as the `withdraw` method.

*The following is all pseudo-code.

First, using a variable `interestPrice` that accumulates each time interest is added.

```solidity
uint interestPrice = 0;
function incrementInterest(uint _value) {
    interestPrice += _value / LockupPropertyValue(address).get(property);
}
```

And add the following variable:

```solidity
mapping(address => uint) lastInterestPrice;
```

`lastInterestPrice` is a save the `interestPrice` at the time, every time a lockup by a user.

And also add the following variable:

```solidity
mapping(address => uint) pendingInterestWithdrawal;
```

`pendingInterestWithdrawal` is a save the withdrawable interest amount at the time, every time the user lockup in additional.

Finally, calculation withdrawable interest amount by the following formula:

```
withdrawable interest amount = ( interestPrice - lastInterestPrice[user] ) * LockupValue(address).get(property, user) + pendingInterestWithdrawal[user];
```

I tried the following spreadsheet to see if the calculation was successful.

https://docs.google.com/spreadsheets/d/1Oznu6uf9lJoYpJSq5bnitgFkBCNP6LaiOk2AoMw_DeM/edit?usp=sharing

**Comment by aggre** [comment]
Note: Interest should be withdrawal at the same time as the lock-up withdraw. (Only interest cannot be withdrawn while locked-up)
