### ISSUE TITLE
test for Oraclize

### ISSUE THREAD

**Issue by theMistletoe** [dev-protocol/protocol#15]
I try to make test for oraclize in Distributor.sol.
In order to run oraclize in local network, you have to use ethereum-bridge.
https://github.com/provable-things/ethereum-bridge
According to above site, in order to run oraclize, running both of  local geth network and ethereum-bridge is needed.

This repository use TravisCI, so in order to realize test for oraclize, we need to establish how to run test execution in parallel process.

I'm thinking about it, but I dont have good ideas now,,,

**Comment by aggre** [comment]
There is [npm-run-all](https://www.npmjs.com/package/npm-run-all) as a way to execute the npm scripts in parallel. Will it help you?

I think we can consider mocking Oraclize.

**Comment by aggre** [comment]
@theMistletoe And, if your PR gets bigger, recommend splitting PR.

**Comment by aggre** [comment]
In [this branch](https://github.com/dev-protocol/repository-token/tree/whitepaper-v1) I'm working on, the whitepaper changes a lot. Because the update turns Oraclize into a third party role, the protocol does not invoke Oraclize.

We will notify you first as your code will maybe not using soon.

**Comment by theMistletoe** [comment]
@aggre I got it. I wait for your merge!!

**Comment by theMistletoe** [comment]
maybe Oraclize doesn't need for new whitepaper.
close this issue.
