### ISSUE TITLE
 WARNING is displayed when running `npm i`

### ISSUE THREAD

**Issue by narita1980** [dev-protocol/protocol#20]
# Problem subject

- [ ] Contracts
- [ ] Tests
- [x] Other

[ If other, please write here problem subject ]

# Description

```
$ npm i
npm WARN @typescript-eslint/eslint-plugin@1.11.0 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @typescript-eslint/parser@1.11.0 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN solium-plugin-security@0.1.1 requires a peer of solium@^1.0.0 but none is installed. You must install peer dependencies yourself.

audited 1507 packages in 2.036s
found 20 vulnerabilities (1 low, 19 high)
  run `npm audit fix` to fix them, or `npm audit` for details
naritanoMacBook-Pro:repository-token narita$ 
```

# Expected behavior/contents

[ Please write here the expected behavior/contents ]

# Actual behavior/contents

[ Please write here the actual behavior/contents ]

# Dev Challenge

Entry to [Dev Challenge](https://github.com/dev-protocol/repository-token/blob/master/docs/DEV_CHALLENGE.md).

- [x] I entry to Dev Challenge with this issue
- [ ] I don't enter to Dev Challenge with this issue

If you enter, please edit the following sections.

## Address

0x27ef834D4A530C8ba24006c88e67524A5d30eD27

# Code of Conduct

By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/dev-protocol/repository-token/blob/master/CODE_OF_CONDUCT.md) 🖖

**Comment by narita1980** [comment]
@aggre 最新版では、WARNING発生しなくなったので本件はクローズしても良いですかね？

**Comment by aggre** [comment]
@narita1980 Yes! クローズします ;)
