### ISSUE TITLE
Testability of Allocator

### ISSUE THREAD

**Issue by aggre** [dev-protocol/protocol#23]
# Description

The Allocator Contract has many state variables so low testability.

# Solution

Improve testability to the Allocator Contract.

# Alternatives/Features

I think ways one of the following is useful:

- Apply Dependency Injection
- Create a testing contract that extends the Allocator and rewrites the state

# Dev Challenge

Entry to [Dev Challenge](https://github.com/dev-protocol/repository-token/blob/master/docs/DEV_CHALLENGE.md).

- [ ] I entry to Dev Challenge with this issue
- [x] I don't enter to Dev Challenge with this issue

# Code of Conduct

By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/dev-protocol/repository-token/blob/master/CODE_OF_CONDUCT.md) 🖖

**Comment by Akira-Taniguchi** [comment]
Now that the test case has been written, this issue will be closed.
