### ISSUE TITLE
What is motivation about voters to Market?

### ISSUE THREAD

**Issue by theMistletoe** [dev-protocol/protocol#27]
Market contract activate by Dev token holder's voting.
When voter votes Dev token to some Market contract for approve,
used Dev token is burnt and decreased.
That' s means voter decrease their Dev token for someone's Market approve.
That doesn't have any good things,  so no one votes, I think.
Is there any merit about voting for voter?

Sorry if I have misunderstood.

**Comment by aggre** [comment]
People who vote for Market is people who think they will benefit from the Market.
For example, if added new Market "YouTube Counts," YouTubers thought will benefit. At that time, YouTuber will reduce their own DEVs in anticipation of increased future DEVs.

**Comment by aggre** [comment]
I notice that if there doesn't burn DEVs by voting, there can also receive a few fees and act as a "voting agent."

In other words, voting requires a burn of DEVs. Or an algorithm that not requires DEVs.

**Comment by theMistletoe** [comment]
> For example, if added new Market "YouTube Counts," YouTubers thought will benefit. At that time, > YouTuber will reduce their own DEVs in anticipation of increased future DEVs.

I've see above meaning.

> In other words, voting requires a burn of DEVs. Or an algorithm that not requires DEVs.

I don't know which is better on incentive design.
I've tried implementation about a burn of DEVs in below.

#28 

Loo PR, and check whether I'm misunderstanding.

**Comment by aggre** [comment]
Thank you for your PR!
I will check the PR.

I am thinking about more better this problem.
What if the proposer of a Market can receive some part of incentives? For example, when developer Alice is can receive 10 DEV by the mint,  proposer of the Market receive 0.1 DEV, Alice receives 9.9 DEV.
In this incentive model, a proposer of the Market has the motivation that buys DEV.

**Comment by aggre** [comment]
According to the current idea, the incentive to proposes and votes a Market is that your assets will become evaluated economically.

This issue is stagnating for a long time, so I close this.
