### ISSUE TITLE
Market's "enabled" should be set in constructor

### ISSUE THREAD

**Issue by theMistletoe** [dev-protocol/protocol#29]
# Description

According to Whitepaper, Market's "enabled" when Market is constructed should be always be false.
Now, Market contract's construstor permits to be given both of true and false, and Factory always gives false.
Maybe it's safe, but this system expect that Market's "enabled" is always "false" when Market is constructed, I think it have better to be set in constructor as "false".

# Solution

You remove second arg from Market, and set "false" to "enabled" in Market's constructor.

# Alternatives/Features

Maintain the status quo.

# Dev Challenge

Entry to [Dev Challenge](https://github.com/dev-protocol/repository-token/blob/master/docs/DEV_CHALLENGE.md).

- [x] I entry to Dev Challenge with this issue
- [ ] I don't enter to Dev Challenge with this issue

If you enter, please edit the following sections.

## Address

0x656b243D73911edAee87779125fEF90c2b1d781f

# Code of Conduct

By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/dev-protocol/repository-token/blob/master/CODE_OF_CONDUCT.md) 🖖

**Comment by aggre** [comment]
Yes, I agree with you.
If it case, what do you think about setting to `false` by the `public` statement?

```sol
public bool enabled = false;
```

**Comment by Akira-Taniguchi** [comment]
Since it has already happened, I will close this issue.
Please contact me if there is a problem.
@theMistletoe @aggre
