### ISSUE TITLE
I wanna use "beforeEach".

### ISSUE THREAD

**Issue by theMistletoe** [dev-protocol/protocol#30]
# Description

I wanna use "beforeEach" in test, but it's regarded as Lint Error by .eslintrc.json.

# Solution

Fix .eslintrc.json

# Alternatives/Features

I Don't know.

# Dev Challenge

Entry to [Dev Challenge](https://github.com/dev-protocol/repository-token/blob/master/docs/DEV_CHALLENGE.md).

- [x] I entry to Dev Challenge with this issue
- [ ] I don't enter to Dev Challenge with this issue

If you enter, please edit the following sections.

## Address

0x656b243D73911edAee87779125fEF90c2b1d781f

# Code of Conduct

By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/dev-protocol/repository-token/blob/master/CODE_OF_CONDUCT.md) 🖖

**Comment by theMistletoe** [comment]
I maybe also wanna use "before","afterEach" and "after".
I wanna set them.

**Comment by aggre** [comment]
Yes, I also think it should be added those to the `globals` of `.eslintrc.json`.

**Comment by theMistletoe** [comment]
I add this on #34 .
if it is closed, close this together.
