### ISSUE TITLE
setting State address on constructing

### ISSUE THREAD

**Issue by theMistletoe** [dev-protocol/protocol#31]
# Description

Almost contract use UseState contract by inheritance.
But, UseState need to set State contract before to use alomost functions in advance.
I often forgot that.
So, I wanna force to set State contract address on constructring the others contract which inherits UseState.

# Solution

add one arg(State's address) to the others contract's constructor which inherits UseState, and call changeStateAddress func

# Alternatives/Features

above idea con't be force to set address.
better idea is force by inheritance.

I don't have good idea yet.

# Dev Challenge

Entry to [Dev Challenge](https://github.com/dev-protocol/repository-token/blob/master/docs/DEV_CHALLENGE.md).

- [x] I entry to Dev Challenge with this issue
- [ ] I don't enter to Dev Challenge with this issue

If you enter, please edit the following sections.

## Address

0x656b243D73911edAee87779125fEF90c2b1d781f

# Code of Conduct

By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/dev-protocol/repository-token/blob/master/CODE_OF_CONDUCT.md) 🖖

**Comment by aggre** [comment]
Yes, I agree with your solution.
It was a hassle to set the address every time, and a cause of the trouble.

**Comment by Akira-Taniguchi** [comment]
Since it has already happened, I will close this issue.
Please contact me if there is a problem.
@theMistletoe @aggre
