### ISSUE TITLE
Property's pay() function's implementation

### ISSUE THREAD

**Issue by theMistletoe** [dev-protocol/protocol#32]
# Description

Property's pay() function is not implemented, yet.
I think execute Withdrawable's increment() function to invest to a Property.
But, Withdrawable's increment() in internal function, so I wanna implement like below solution.

# Solution

Allocator execute investment to Property.
Property call above function, so above function shoud be limited only Property.
Look below image.

![UML](http://www.plantuml.com/plantuml/png/LP0zJi0m38NtdC8RFw8Ng1ZA3P00iR2agQ6HN2TAN4ebPcREo4cmWXhIfRNipyzvRyXYawmBcMSlyvJiPaT2kFtiu8ueE2iXcLh1TGSFOWLD-HRiAUDVwoXAzpw5Y4dsismFdWKJMzB29LoGvVAgqUyXhYDv1u5fFpIKVSUiuC_ND-DcQh_IqUugmq6FIuWGNg5XoX3m0zsgythh8bVTqsRpc0hKxTPDQm5kNlXnzhc0e7_oYnUSYW_GYDzG_ZCPa2UD_1S0 "UML")

# Alternatives/Features

I don't have any idea, yet.

# Dev Challenge

Entry to [Dev Challenge](https://github.com/dev-protocol/repository-token/blob/master/docs/DEV_CHALLENGE.md).

- [x] I entry to Dev Challenge with this issue
- [ ] I don't enter to Dev Challenge with this issue

If you enter, please edit the following sections.

## Address

0x656b243D73911edAee87779125fEF90c2b1d781f

# Code of Conduct

By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/dev-protocol/repository-token/blob/master/CODE_OF_CONDUCT.md) 🖖

**Comment by theMistletoe** [comment]
I'm thinking about this, I don't wanna call increment() from Property via Allocator.
In Allocator function, can't get executor's address, so restricting increment() function call becomes difficult.
As below image, changing to call directly function from Allocator solves that problem.

![UML2](http://www.plantuml.com/plantuml/png/PO-nJiGm44HxVyLsND11WGG5eZWaFW098PfhVFOSYN3MqNgT0ucQcc_aIx3H9Rg8RZDvC-FP9BMYkG_cfTFMYptONG3TVLxGVGZHMOrYdjGgwFo_LB7dXByFKuzPVPGuGFHZgSx-PTijTQmGjg4SJj23TTMOcIx0a7UXS-NtYAGhwxqW9HgEBUiQS7LzGwCD6StFrpVZOAOt5FlHO3WgIED0SK-dyIdsg4i4xt1PCHKrv3k1quvVvqbdQOgxt781QP-v497Nv5guDz8MPFkOjROyODooPKzJycBvwTmDsES-_080 "UML2")

**Comment by theMistletoe** [comment]
I'm wrong.
State has isProperty() function, so using it can restricts allocator's caller by Property address

**Comment by aggre** [comment]
Thank you for issuing the problem.
Should be required Property's `pay()` function runs Allocator's `increment()` function.
But, Allocator's `increment()` function is an internal method, as you said.

I thought of some way to solve it.

- Move `pay()` function to Allocator.
- Add `incrementByPayment() // a fictitious name` to Allocator, the function is only execute from Property can it. // Using `isProperty()` as you said.

**Comment by theMistletoe** [comment]
I open PR #34 .
I choose second.
