### ISSUE TITLE
Sometimes it fails to `allocation`

### ISSUE THREAD

**Issue by aggre** [dev-protocol/protocol#386]
# Problem subject

- [x] Contracts
- [ ] Tests
- [ ] Other

# Description

`Allocator.allocation` fails by `Decimals.outOf` when Metrics has an asset value of less than 1/10^18 of the total asset value.

https://github.com/dev-protocol/protocol/blob/0a32dd4b12609b6d66edda5f87d5806fac33deb1/contracts/src/allocator/Allocator.sol#L164-L183

# Expected behavior/contents

Fix `Decimals.outOf` like the following:
```solidity
function outOf(uint256 _a, uint256 _b)
	internal
	pure
	returns (uint256 result)
{
	uint256 a = _a.mul(basisValue);
	if (a < _b) {
		return 0;
	}
	return (a.div(_b));
}
```

# Actual behavior/contents

https://github.com/dev-protocol/protocol/blob/0a32dd4b12609b6d66edda5f87d5806fac33deb1/contracts/src/common/libs/Decimals.sol#L10-L21

# Code of Conduct

By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/dev-protocol/repository-token/blob/master/CODE_OF_CONDUCT.md) 🖖

**Comment by Akira-Taniguchi** [comment]
memo

The outOf function is also used in lockup and withdraw contracts.
I have confirmed that it is not a problem even if we modify it to return 0 instead of error in this modification.

@aggre

**Comment by aggre** [comment]
@Akira-Taniguchi Thank you for your confirmation!
