### ISSUE TITLE
A build error has occurred in travis ci

### ISSUE THREAD

**Issue by Akira-Taniguchi** [dev-protocol/protocol#41]
# Problem subject

- [ ] Contracts
- [ ] Tests
- [x] Other

# Description

https://travis-ci.org/dev-protocol/protocol/jobs/601613058#L237
maybe... build error by Sha3

# Expected behavior/contents

Travis ci runs without error

# Actual behavior/contents

A build error has occurred in travis ci

# Dev Challenge

- [x] I entry to Dev Challenge with this issue
- [ ] I don't enter to Dev Challenge with this issue

## Address

0xA717AA5E8858cA5836Fef082E6B2965ba0dB615d

**Comment by theMistletoe** [comment]
maybe because of node 13.0.0 isn't suppoerted?

https://github.com/phusion/node-sha3/issues/32

**Comment by theMistletoe** [comment]
travisci can specify node version via nvm like below.

https://qiita.com/Linda_pp/items/2f32716d534c97685ab1
