### ISSUE TITLE
Allocator's initialPaymentBlock is always Zero.

### ISSUE THREAD

**Issue by theMistletoe** [dev-protocol/protocol#51]
# Problem subject

- [x] Contracts
- [ ] Tests
- [ ] Other

# Description

Allocator's initialPaymentBlock is always Zero.
It expects has some natural number.

```solidity
uint256 public initialPaymentBlock;
```

```solidity
uint256 totalPaymentsPerBlock = totalPaymentValue /
			(block.number - initialPaymentBlock);
```

# Expected behavior/contents

I don't know how much number is supplied and when.

# Actual behavior/contents

above codes.

# Dev Challenge

Entry to [Dev Challenge](https://github.com/dev-protocol/repository-token/blob/master/docs/DEV_CHALLENGE.md).

- [x] I entry to Dev Challenge with this issue
- [ ] I don't enter to Dev Challenge with this issue

If you enter, please edit the following sections.

## Address

0x656b243D73911edAee87779125fEF90c2b1d781f

# Code of Conduct

By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/dev-protocol/repository-token/blob/master/CODE_OF_CONDUCT.md) 🖖

**Comment by aggre** [comment]
Yeah, exactly, you are right.

But `initialPaymentBlock` is not necessary now because released the new whitepaper. https://github.com/dev-protocol/protocol/pull/56
