### ISSUE TITLE
Allocator's updateAllocateValue called by investToProperty.

### ISSUE THREAD

**Issue by theMistletoe** [dev-protocol/protocol#52]
# Description

Allocator's "updateAllocateValue" should be executed by "investToProperty".
According to whitepaper, it is executed by "Property's pay function".
But, I changed it is executed by Allocator by PR #34 .
so, updateAllocateValue had better call after investToProperty.
I think fix whitepaper, too.

# Solution

- make updateAllocateValue function private.
- updateAllocateValue had better call after investToProperty.

# Alternatives/Features

I don't know.

# Dev Challenge

Entry to [Dev Challenge](https://github.com/dev-protocol/repository-token/blob/master/docs/DEV_CHALLENGE.md).

- [x] I entry to Dev Challenge with this issue
- [ ] I don't enter to Dev Challenge with this issue

If you enter, please edit the following sections.

## Address

0x656b243D73911edAee87779125fEF90c2b1d781f

# Code of Conduct

By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/dev-protocol/repository-token/blob/master/CODE_OF_CONDUCT.md) 🖖

**Comment by aggre** [comment]
Thank you for your report issue.

Your exact issue has always helped us.

But `investToProperty` and `updateAllocateValue ` are not necessary now because released the new whitepaper.
https://github.com/dev-protocol/protocol/pull/56
