### ISSUE TITLE
Unlocked Pragma

### ISSUE THREAD

**Issue by aggre** [dev-protocol/protocol#547]
# Problem subject

- [x] Contracts
- [ ] Tests
- [ ] Other

# Description

File(s) affected: Allocator.sol IAllocator.sol AddressConfig.sol UsingConfig.sol IGroup.sol Decimals.sol Killable.sol, EternalStorage.sol UsingStorage.sol AddressValidator.sol UsingValidator.sol Dev.sol DevMigration.sol ILockup.sol, Lockup.sol LockupStorage.sol IMarket.sol IMarketBehavior.sol IMarketFactory.sol IMarketGroup.sol Market.sol, MarketFactory.sol MarketGroup.sol IMetricsFactory.sol IMetricsGroup.sol Metrics.sol MetricsFactory.sol, MetricsGroup.sol DIP1.sol DIP3.sol DIP7.sol IPolicy.sol IPolicyFactory.sol IPolicyGroup.sol IPolicySet.sol, PolicyFactory.sol PolicyGroup.sol PolicySet.sol TheFirstPolicy.sol IProperty.sol IPropertyFactory.sol, Property.sol PropertyFactory.sol PropertyGroup.sol IVoteCounter.sol VoteCounter.sol VoteCounterStorage.sol
IWithdraw.sol Withdraw.sol WithdrawStorage.sol test/*.sol

Every Solidity file specifies in the header a version number of the format `pragma solidity (^)0.4.*`. The caret (`^`) before the version number implies an unlocked pragma, meaning that the compiler will use the specified version and above, hence the term "unlocked." For consistency and to prevent unexpected behavior in the future, it is recommended to remove the caret to lock the file onto a specific Solidity version.

# Expected behavior/contents

`pragma solidity 0.5.17;`

# Actual behavior/contents

[ Please write here the actual behavior/contents ]

# Code of Conduct

By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/dev-protocol/repository-token/blob/master/CODE_OF_CONDUCT.md) 🖖

**Comment by Akira-Taniguchi** [comment]
Dev.sol and AddressConfig.sol are not subject to pragma fixation.

reason:Since the AddressConfig is referenced by existing Property and Dev contracts, the old AddressCoonfig cannot be completely truncated.
If this happens, the old AddressConfig and the new AddressConfig will continue to be in a state of double maintenance, which will increase operational costs and likely lead to work errors.
