### ISSUE TITLE
Withdrawing method for lockers is not implemented

### ISSUE THREAD

**Issue by aggre** [dev-protocol/protocol#59]
# Problem subject

- [x] Contracts
- [ ] Tests
- [ ] Other

# Description

From whitepaper v2.x, use lockups instead of payments.

There is no way for people who locking-up to receive rewards.

# Code of Conduct

By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/dev-protocol/repository-token/blob/master/CODE_OF_CONDUCT.md) 🖖

**Comment by Akira-Taniguchi** [comment]
Duplicate of #140
