### ISSUE TITLE
A better way to call `authenticatedCallback` function in Market from Market Behavior

### ISSUE THREAD

**Issue by aggre** [dev-protocol/protocol#65]
# Problem subject

- [x] Contracts
- [ ] Tests
- [ ] Other

# Description

Market Behavior needs to call the `authenticatedCallback` method of the Market Contract to which it belongs.

I think it's like a bad pattern. There is no inheritance relationship between Market Behavior and the Market, but it looks as if the child class calls the parent class.

# Code of Conduct

By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/dev-protocol/repository-token/blob/master/CODE_OF_CONDUCT.md) 🖖

**Comment by aggre** [comment]
Note: In the first place, a way to call `authenticatedCallback` method in Market from Market Behavior is not implemented yet.

**Comment by theMistletoe** [comment]
```authenticatedCallback``` is supposed to be called when authentication is succeed in ```authenticate``` .

```authenticatedCallback``` returns bool value.
so how's calling ```authenticatedCallback``` when ```authenticatedCallback``` returns true?

Like below.

```solidity
bool isSuccess = Behavior(behavior).authenticate(
			_prop,
			_args1,
			_args2,
			_args3,
			_args4,
			_args5
		);

		if (isSuccess) {
			authenticatedCallback(_prop);
		}
```

**Comment by aggre** [comment]
@theMistletoe `authenticatedCallback` method is called **from** the `authenticate` method in a Market Behavior. It's a call from the `authenticate` method, and it's may asynchronously logic, so the protocol isn't decided the timing. `authenticate` method is just a trigger for authentication, so its return value means not issued an error.
