### ISSUE TITLE
Who is supporsed to decided Repository.sol's name and symbol?

### ISSUE THREAD

**Issue by theMistletoe** [dev-protocol/protocol#9]
Repository.sol inherits ERC20Detailed, so it needs name and symbol in constructor,
Now, actual content supposeed to be "package" (maybe npm package URL).(in ReposioryFactory's implement)
According to OpenZeppelin, using short name about npm package is more better, I think.
https://docs.openzeppelin.org/v2.3.0/api/token/erc20#erc20detailed

Should name and symbol be decided by npm package owner?
In the case, I think name and symbol had better be added to createRepository's args.
ReposioryFactory's function "createRepository" is supporsed to be kicked by who?

**Comment by aggre** [comment]
First, It is the OSS author who kicks `createRepository`.

And, Repository.sol does not have enough implementation.

The package name contains the string that unexpected as a token symbol. (e.g. `@`, `/` and `-`)
How to handle these strings is a complicated problem.

As you wrote, I think symbols should be left to the transaction sender. But I think about the name is package name better. Usability improves by more less arguments.

**Comment by theMistletoe** [comment]
I've understood this problem.

> The package name contains the string that unexpected as a token symbol. (e.g. @, / and -)

What does this mean?
solidity's string accepts these charactors.
If I can extract package name from URL, can I solve this problem?

**Comment by aggre** [comment]
In general, token symbols should short.
I think that the token name(not a symbol) is not a problem even for long strings.

**Comment by theMistletoe** [comment]
whitepaper has changed, so Repository.sol changed to Prooerty.sol.(Factory contract too.)
PropertyFactory contract changed like give name and symbol to Property.sol, so this issue has resolved, I think.
I close this.
